import 'package:controle_total_premium/services/yearly_commitment_repeat_service.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('YearlyCommitmentRepeatService', () {
    test('shouldShowInAgendaList oculta modelo e mostra ocorrência', () {
      expect(
        YearlyCommitmentRepeatService.shouldShowInAgendaList(
          {'isYearlyRepeatTemplate': true, 'repeatYearly': true},
          docId: 'tpl123',
        ),
        isFalse,
      );
      expect(
        YearlyCommitmentRepeatService.shouldShowInAgendaList(
          {
            'repeatYearly': true,
            'yearlyRepeatTemplateId': 'tpl123',
            'yearlyRepeatInstanceYear': 2026,
          },
          docId: 'tpl123_y2026',
        ),
        isTrue,
      );
      expect(
        YearlyCommitmentRepeatService.shouldShowInAgendaList(
          {'repeatYearly': true},
          docId: 'fantasma_sem_ano',
        ),
        isFalse,
      );
    });

    test('instanceDocId — 1 ocorrência por ano (data fixa)', () {
      expect(
        YearlyCommitmentRepeatService.instanceDocId('abc', 2026),
        'abc_y2026',
      );
    });

    test('instanceDocId — várias datas no ano (dias da semana)', () {
      expect(
        YearlyCommitmentRepeatService.instanceDocId(
          'abc',
          2026,
          month: 5,
          day: 24,
        ),
        'abc_y2026m05d24',
      );
    });

    test('isAutoGeneratedWeddingAnniversaryTitle detecta título automático', () {
      expect(
        YearlyCommitmentRepeatService.isAutoGeneratedWeddingAnniversaryTitle(
          'ANIVERSÁRIO DE CASAMENTO',
        ),
        isTrue,
      );
      expect(
        YearlyCommitmentRepeatService.isAutoGeneratedWeddingAnniversaryTitle(
          'CASAMENTO',
        ),
        isFalse,
      );
    });

    test('isLikelyAutoSimilarTitle — não duplica título do usuário', () {
      expect(
        YearlyCommitmentRepeatService.isLikelyAutoSimilarTitle(
          'CASAMENTO',
          'ANIVERSÁRIO DE CASAMENTO',
        ),
        isTrue,
      );
      expect(
        YearlyCommitmentRepeatService.isLikelyAutoSimilarTitle(
          'JOÃO SILVA',
          'ANIVERSÁRIO DE JOÃO SILVA',
        ),
        isTrue,
      );
      expect(
        YearlyCommitmentRepeatService.isLikelyAutoSimilarTitle(
          'CASAMENTO',
          'REUNIÃO DE TRABALHO',
        ),
        isFalse,
      );
      expect(
        YearlyCommitmentRepeatService.isLikelyAutoSimilarTitle(
          'CASAMENTO',
          'CASAMENTO',
        ),
        isTrue,
      );
    });
  });
}
