import 'dart:async';

import 'package:cloud_firestore/cloud_firestore.dart';

import '../constants/commitment_symbols.dart';
import '../models/despertar_item.dart';
import '../utils/agenda_delivery_reset.dart';

import 'agenda_notification_reschedule_helper.dart';

import 'agenda_notifications_refresher.dart';

import 'agenda_scale_mirror_service.dart';

import 'express_compromisso_agenda_sync.dart';

/// Compromisso particular com repetição anual (aniversário, casamento, data fixa

/// ou dias da semana em todo o ano — ex.: toda quarta e quinta).

///

/// - Documento **modelo** em `reminders` (`isYearlyRepeatTemplate: true`) — não lista na UI.

/// - Repetição anual replica **exatamente** título/horário/cor que o usuário escreveu —
///   sem criar outro compromisso similar no mesmo dia.

class YearlyCommitmentRepeatService {
  YearlyCommitmentRepeatService._();

  static const int _yearsBack = 1;

  static const int _yearsForward = 6;

  static const String yearlyNotesMarker = '🔁 Repete todo ano';

  /// Compromisso com repetição anual (modelo ou ocorrência de um ano).

  static bool isYearlyRepeatEntry(Map<String, dynamic> data) {
    if (data['repeatYearly'] == true) return true;

    if (data['isYearlyRepeatTemplate'] == true) return true;

    return (data['yearlyRepeatTemplateId'] ?? '').toString().trim().isNotEmpty;
  }

  /// Só ocorrências concretas entram na Agenda / Painel (evita duplicar modelo + ano).

  static bool shouldShowInAgendaList(
    Map<String, dynamic> data, {
    String? docId,
  }) {
    if (data['isYearlyRepeatTemplate'] == true) return false;

    if ((data['source'] ?? '').toString() == 'yearly_repeat_template') {
      return false;
    }

    if (!isYearlyRepeatEntry(data)) return true;

    if (docId != null && isYearlyInstanceDocId(docId)) return true;

    return instanceYearFromData(data, docId: docId) != null;
  }

  static bool isYearlyInstanceDocId(String docId) =>
      RegExp(r'_y\d{4}(?:m\d{2}d\d{2})?$').hasMatch(docId);

  static int? instanceYearFromData(
    Map<String, dynamic> data, {
    String? docId,
  }) {
    final y = data['yearlyRepeatInstanceYear'];

    if (y is num) return y.toInt();

    if (docId != null) {
      final m = RegExp(r'_y(\d{4})').firstMatch(docId);

      if (m != null) return int.tryParse(m.group(1)!);
    }

    return null;
  }

  static List<int> weekdaysFromData(Map<String, dynamic> data) {
    final raw = data['yearlyRepeatWeekdays'];

    if (raw is! List) return const [];

    final out = <int>{};

    for (final e in raw) {
      if (e is num) {
        final w = e.toInt();

        if (w >= DateTime.monday && w <= DateTime.sunday) out.add(w);
      }
    }

    return out.toList()..sort();
  }

  /// Datas excluídas (yyyy-MM-dd) — séries por dia da semana têm várias
  /// ocorrências no ano: apagar uma só não pode excluir o ANO inteiro.
  static Set<String> excludedDatesFromData(Map<String, dynamic> data) {
    final raw = data['yearlyRepeatExcludedDates'];
    if (raw is! List) return {};
    return raw.map((e) => e.toString().trim()).where((e) => e.isNotEmpty).toSet();
  }

  static String excludedDateKey(DateTime d) =>
      '${d.year.toString().padLeft(4, '0')}-${d.month.toString().padLeft(2, '0')}-${d.day.toString().padLeft(2, '0')}';

  static final RegExp _instanceDayIdRe = RegExp(r'_y(\d{4})m(\d{2})d(\d{2})$');

  static Set<int> excludedYearsFromData(Map<String, dynamic> data) {
    final raw = data['yearlyRepeatExcludedYears'];

    if (raw is! List) return {};

    return raw
        .map((e) => e is num ? e.toInt() : int.tryParse('$e'))
        .whereType<int>()
        .toSet();
  }

  static String formatAnchorDayMonth(int month, int day) =>
      '${day.toString().padLeft(2, '0')}/${month.toString().padLeft(2, '0')}';

  static String buildYearlyRepeatNotesLine(int month, int day) =>
      '$yearlyNotesMarker em ${formatAnchorDayMonth(month, day)}. '
      'Série anual: aparece no calendário de Escalas e neste módulo.';

  static String stripYearlyRepeatLines(String notes) {
    return notes
        .split('\n')
        .where((l) => !l.contains(yearlyNotesMarker))
        .join('\n')
        .trim();
  }

  static String mergeUserNotesWithYearlyLine({
    required String userNotes,
    required int month,
    required int day,
  }) {
    final clean = stripYearlyRepeatLines(userNotes);

    final line = buildYearlyRepeatNotesLine(month, day);

    if (clean.isEmpty) return line;

    return '$clean\n\n$line';
  }

  static String _normTitle(String title) => title.trim().toLowerCase();

  /// Título que o app **não** deve inventar (ex.: «Aniversário de Casamento» ao salvar «Casamento»).
  static bool isAutoGeneratedWeddingAnniversaryTitle(String title) {
    final t = _normTitle(title);
    if (t.isEmpty) return false;
    if (t == 'aniversário de casamento' || t == 'aniversario de casamento') {
      return true;
    }
    if (t == 'aniversário do casamento' || t == 'aniversario do casamento') {
      return true;
    }
    return t.contains('anivers') && t.contains('casamento') && t != 'casamento';
  }

  /// Outro título na mesma data que parece cópia automática do que o usuário escreveu.
  static bool isLikelyAutoSimilarTitle(String keepTitle, String otherTitle) {
    final keep = _normTitle(keepTitle);
    final other = _normTitle(otherTitle);
    if (keep.isEmpty || other.isEmpty) return false;
    if (keep == other) return true;

    if (isAutoGeneratedWeddingAnniversaryTitle(other) &&
        (keep == 'casamento' || keep.contains('casamento'))) {
      return true;
    }

    for (final prefix in [
      'aniversário de ',
      'aniversario de ',
      'aniversário do ',
      'aniversario do '
    ]) {
      if (!other.startsWith(prefix)) continue;
      final base = other.substring(prefix.length).trim();
      if (base.isEmpty) continue;
      if (base == keep || keep.contains(base) || base.contains(keep)) {
        return true;
      }
    }

    return false;
  }

  static bool _sameYearlyAnchor(
    Map<String, dynamic> data,
    int anchorMonth,
    int anchorDay,
  ) {
    final m = (data['yearlyRepeatMonth'] as num?)?.toInt() ??
        (data['date'] as Timestamp?)?.toDate().month;
    final d = (data['yearlyRepeatDay'] as num?)?.toInt() ??
        (data['date'] as Timestamp?)?.toDate().day;
    return m == anchorMonth && d == anchorDay;
  }

  /// O doc pertence à MESMA série (modelo `keepTemplateId`)?
  ///
  /// Só pelo vínculo explícito: campo `yearlyRepeatTemplateId` ou ID de ocorrência
  /// `{templateId}_y…`. Título NUNCA decide sozinho.
  static bool belongsToSeries({
    required String docId,
    required Map<String, dynamic> data,
    required String templateId,
  }) {
    if (templateId.isEmpty) return false;
    if (docId == templateId) return true;
    final tid = (data['yearlyRepeatTemplateId'] ?? '').toString().trim();
    if (tid.isNotEmpty) return tid == templateId;
    return isYearlyInstanceDocId(docId) && docId.startsWith('${templateId}_y');
  }

  /// Decide se um doc é «mestre fantasma» legado da série que está sendo mantida.
  ///
  /// Regras (correção de perda de dados — antes apagava compromissos comuns e
  /// outras séries anuais com título parecido):
  /// - nunca toca em item não-anual (`repeatYearly` ausente/false);
  /// - nunca toca em outro modelo anual (cada modelo é uma série independente);
  /// - nunca toca em ocorrência `_yAAAA` (ocorrências são podadas pelo próprio modelo);
  /// - vínculo `yearlyRepeatTemplateId` de OUTRA série → nunca;
  /// - vínculo com a própria série → pode limpar (cópia fantasma do 1.º ano);
  /// - sem vínculo (legado): só com título EXATAMENTE igual, mesma data âncora.
  static bool isGhostOfSeries({
    required String docId,
    required Map<String, dynamic> data,
    required String keepTemplateId,
    required String keepTitle,
    required int anchorMonth,
    required int anchorDay,
  }) {
    if (keepTemplateId.isEmpty || docId == keepTemplateId) return false;
    if (data['repeatYearly'] != true) return false;
    if (data['isYearlyRepeatTemplate'] == true) return false;
    if ((data['source'] ?? '').toString() == 'yearly_repeat_template') {
      return false;
    }
    if (isYearlyInstanceDocId(docId)) return false;
    final tid = (data['yearlyRepeatTemplateId'] ?? '').toString().trim();
    if (tid.isNotEmpty) return tid == keepTemplateId;
    if (!_sameYearlyAnchor(data, anchorMonth, anchorDay)) return false;
    final keepNorm = _normTitle(keepTitle);
    if (keepNorm.isEmpty) return false;
    return _normTitle((data['title'] ?? '').toString()) == keepNorm;
  }

  /// Limpa só restos da PRÓPRIA série (mestre fantasma legado) na mesma data.
  ///
  /// Antes apagava compromissos comuns e outras séries anuais com título parecido
  /// (ex.: «Aniversário de João» × «João») e duas séries com o mesmo título se
  /// apagavam entre si ao abrir Escalas — perda de dados. Agora só o vínculo da
  /// série decide (ver [isGhostOfSeries]).
  static Future<void> _purgeForeignYearlyOnSameAnchor({
    required String userDocId,
    required String keepTemplateId,
    required String keepTitle,
    required int anchorMonth,
    required int anchorDay,
  }) async {
    if (userDocId.isEmpty || keepTemplateId.isEmpty) return;

    try {
      final snap = await _reminders(userDocId)
          .where('repeatYearly', isEqualTo: true)
          .get();
      for (final doc in snap.docs) {
        if (!isGhostOfSeries(
          docId: doc.id,
          data: doc.data(),
          keepTemplateId: keepTemplateId,
          keepTitle: keepTitle,
          anchorMonth: anchorMonth,
          anchorDay: anchorDay,
        )) {
          continue;
        }
        await _deleteYearlyOccurrenceAndMirror(
          userDocId: userDocId,
          reminderId: doc.id,
        );
      }
    } catch (_) {}
  }

  static CollectionReference<Map<String, dynamic>> _reminders(String uid) =>
      FirebaseFirestore.instance
          .collection('users')
          .doc(uid)
          .collection('reminders');

  static String instanceDocId(
    String templateId,
    int year, {
    int? month,
    int? day,
  }) {
    if (month != null && day != null) {
      return '${templateId}_y${year}m${month.toString().padLeft(2, '0')}d${day.toString().padLeft(2, '0')}';
    }

    return '${templateId}_y$year';
  }

  static DateTime anchorDate(int year, int month, int day) {
    final last = DateTime(year, month + 1, 0).day;

    final d = day.clamp(1, last);

    return DateTime(year, month, d);
  }

  /// Garante ocorrências para todos os modelos do usuário (chamar ao abrir Escalas / Agenda).

  static Future<void>? _syncInFlight;
  static String? _syncUserId;
  static DateTime? _lastCompletedAt;
  static const _kSyncMinInterval = Duration(minutes: 10);

  static Future<void> ensureAllTemplatesSynced(String userDocId) async {
    if (userDocId.isEmpty) return;

    final last = _lastCompletedAt;
    if (_syncUserId == userDocId &&
        last != null &&
        DateTime.now().difference(last) < _kSyncMinInterval) {
      return;
    }

    if (_syncInFlight != null && _syncUserId == userDocId) {
      return _syncInFlight!;
    }

    _syncUserId = userDocId;
    _syncInFlight = _ensureAllTemplatesSyncedBody(userDocId);
    try {
      await _syncInFlight;
      _lastCompletedAt = DateTime.now();
    } finally {
      _syncInFlight = null;
    }
  }

  static Future<void> _ensureAllTemplatesSyncedBody(String userDocId) async {
    try {
      final snap = await _reminders(userDocId)
          .where('isYearlyRepeatTemplate', isEqualTo: true)
          .get();

      for (final doc in snap.docs) {
        await syncInstancesFromTemplate(
          userDocId: userDocId,
          templateId: doc.id,
          templateData: doc.data(),
        );
        await _purgeTemplateFromCalendar(
          userDocId: userDocId,
          templateId: doc.id,
        );
        final data = doc.data();
        final m = (data['yearlyRepeatMonth'] as num?)?.toInt() ??
            (data['date'] as Timestamp?)?.toDate().month ??
            1;
        final d = (data['yearlyRepeatDay'] as num?)?.toInt() ??
            (data['date'] as Timestamp?)?.toDate().day ??
            1;
        await _purgeForeignYearlyOnSameAnchor(
          userDocId: userDocId,
          keepTemplateId: doc.id,
          keepTitle: (data['title'] ?? '').toString(),
          anchorMonth: m,
          anchorDay: d,
        );
      }
    } catch (_) {}
  }

  /// Modelo anual não deve aparecer no calendário de Escalas — só ocorrências.
  /// Apenas remove o espelho `agenda_{templateId}` — **nunca** apaga o doc modelo.
  static Future<void> _purgeTemplateFromCalendar({
    required String userDocId,
    required String templateId,
  }) async {
    if (userDocId.isEmpty || templateId.isEmpty) return;
    await AgendaScaleMirrorService.delete(
      userDocId: userDocId,
      agendaId: templateId,
    );
  }

  /// Remove reminder + espelho (só ocorrências / fantasmas — não o modelo).
  static Future<void> _deleteYearlyOccurrenceAndMirror({
    required String userDocId,
    required String reminderId,
  }) async {
    if (userDocId.isEmpty || reminderId.isEmpty) return;
    await ExpressCompromissoAgendaSync.deleteLinkedFromScaleDoc(
      userDocId: userDocId,
      scaleDocId: ExpressCompromissoAgendaSync.scaleDocId(reminderId),
    );
    try {
      await _reminders(userDocId).doc(reminderId).delete();
    } catch (_) {}
    await AgendaScaleMirrorService.delete(
      userDocId: userDocId,
      agendaId: reminderId,
    );
  }

  /// Após sync: 1 ocorrência por ano (sem cópia fantasma do modelo no 1.º ano).
  static Future<void> _dedupeYearlySeriesAfterSync({
    required String userDocId,
    required String templateId,
    required Set<String> expectedInstanceIds,
    required int anchorMonth,
    required int anchorDay,
  }) async {
    await _purgeTemplateFromCalendar(
      userDocId: userDocId,
      templateId: templateId,
    );

    try {
      final linked = await _reminders(userDocId)
          .where('yearlyRepeatTemplateId', isEqualTo: templateId)
          .get();
      for (final doc in linked.docs) {
        if (doc.id == templateId) continue;
        if (expectedInstanceIds.contains(doc.id)) continue;
        await _deleteYearlyOccurrenceAndMirror(
          userDocId: userDocId,
          reminderId: doc.id,
        );
      }
    } catch (_) {}

    await _removeLegacyDuplicateMasters(
      userDocId: userDocId,
      templateId: templateId,
      anchorMonth: anchorMonth,
      anchorDay: anchorDay,
    );
  }

  /// Cria modelo + ocorrências. Retorna o ID do modelo.

  static Future<String> createWithYearlyRepeat({
    required String userDocId,
    required String title,
    required String notes,
    required DateTime anchorCalendarDay,
    required String startHHmm,
    required String endHHmm,
    required String colorHex,
    List<int>? reminderLeads,
    String? notificationSoundId,
    String? notificationDeliveryMode,
    List<int>? yearlyRepeatWeekdays,
    Map<String, dynamic>? despertar,
    String? commitmentSymbol,
  }) async {
    final ref = _reminders(userDocId).doc();

    final templateId = ref.id;

    final month = anchorCalendarDay.month;

    final day = anchorCalendarDay.day;

    final notesMerged = mergeUserNotesWithYearlyLine(
      userNotes: notes,
      month: month,
      day: day,
    );

    final template = _basePayload(
      title: title,
      notes: notesMerged,
      startHHmm: startHHmm,
      endHHmm: endHHmm,
      colorHex: colorHex,
      reminderLeads: reminderLeads,
      notificationSoundId: notificationSoundId,
      notificationDeliveryMode: notificationDeliveryMode,
      month: month,
      day: day,
      isTemplate: true,
      templateId: templateId,
      instanceYear: null,
      yearlyRepeatWeekdays: yearlyRepeatWeekdays,
    );
    // «Despertar» por item: o da série vale para todas as ocorrências.
    if (despertar != null) template[DespertarItem.campo] = despertar;
    // Emoji/ícone da série — copiado para cada ocorrência e espelho.
    final simbolo = (commitmentSymbol ?? '').trim();
    if (simbolo.isNotEmpty) template[kCommitmentSymbolField] = simbolo;

    await ref.set(template);

    await syncInstancesFromTemplate(
      userDocId: userDocId,
      templateId: templateId,
      templateData: template,
    );

    await _purgeForeignYearlyOnSameAnchor(
      userDocId: userDocId,
      keepTemplateId: templateId,
      keepTitle: title,
      anchorMonth: month,
      anchorDay: day,
    );

    await _purgeTemplateFromCalendar(
      userDocId: userDocId,
      templateId: templateId,
    );

    unawaited(AgendaNotificationRescheduleHelper.afterItemChanged(
      userDocId: userDocId,
      queueRebuild: true,
    ));

    return templateId;
  }

  /// Data/hora/dias da semana da série mudaram (exige limpar calendário e recriar anos).

  static bool seriesPlanChanged({
    required Map<String, dynamic>? before,
    required int month,
    required int day,
    required String startHHmm,
    required String endHHmm,
    required List<int> weekdays,
  }) {
    if (before == null) return true;

    final bMonth = (before['yearlyRepeatMonth'] as num?)?.toInt();

    final bDay = (before['yearlyRepeatDay'] as num?)?.toInt();

    if (bMonth != month || bDay != day) return true;

    if ((before['time'] ?? '').toString() != startHHmm) return true;

    if ((before['endTime'] ?? '').toString() != endHHmm) return true;

    final bWd = weekdaysFromData(before);

    if (bWd.length != weekdays.length) return true;

    for (var i = 0; i < weekdays.length; i++) {
      if (bWd[i] != weekdays[i]) return true;
    }

    return false;
  }

  /// Atualiza modelo e re-sincroniza anos (a partir do ano da data editada).

  static Future<void> updateYearlySeries({
    required String userDocId,
    required String templateId,
    required String title,
    required String notes,
    required DateTime anchorCalendarDay,
    required String startHHmm,
    required String endHHmm,
    required String colorHex,
    List<int>? reminderLeads,
    String? notificationSoundId,
    String? notificationDeliveryMode,
    List<int>? yearlyRepeatWeekdays,
    Map<String, dynamic>? despertar,
    String? commitmentSymbol,
  }) async {
    Map<String, dynamic>? templateBefore;

    try {
      final snap = await _reminders(userDocId).doc(templateId).get();

      templateBefore = snap.data();
    } catch (_) {}

    final month = anchorCalendarDay.month;

    final day = anchorCalendarDay.day;

    final weekdays = yearlyRepeatWeekdays ?? const <int>[];

    final planChanged = seriesPlanChanged(
      before: templateBefore,
      month: month,
      day: day,
      startHHmm: startHHmm,
      endHHmm: endHHmm,
      weekdays: weekdays,
    );

    final notesMerged = mergeUserNotesWithYearlyLine(
      userNotes: notes,
      month: month,
      day: day,
    );

    final template = _basePayload(
      title: title,
      notes: notesMerged,
      startHHmm: startHHmm,
      endHHmm: endHHmm,
      colorHex: colorHex,
      reminderLeads: reminderLeads,
      notificationSoundId: notificationSoundId,
      notificationDeliveryMode: notificationDeliveryMode,
      month: month,
      day: day,
      isTemplate: true,
      templateId: templateId,
      instanceYear: null,
      yearlyRepeatWeekdays: yearlyRepeatWeekdays,
      excludedYears:
          templateBefore != null ? excludedYearsFromData(templateBefore) : null,
      excludedDates:
          templateBefore != null ? excludedDatesFromData(templateBefore) : null,
    );

    if (weekdays.isEmpty) {
      template['yearlyRepeatWeekdays'] = FieldValue.delete();
    }
    template['reminderLeads'] = FieldValue.delete();
    template['notificationSoundId'] = FieldValue.delete();
    template['notificationDeliveryMode'] = FieldValue.delete();
    // «Despertar» por item: o da série vale para todas as ocorrências.
    if (despertar != null) template[DespertarItem.campo] = despertar;
    // Emoji/ícone: null = não mexe; vazio = volta ao automático pelo título.
    if (commitmentSymbol != null) {
      final simbolo = commitmentSymbol.trim();
      template[kCommitmentSymbolField] =
          simbolo.isEmpty ? FieldValue.delete() : simbolo;
    }

    if (planChanged) {
      await _clearAllInstancesFromCalendar(
        userDocId: userDocId,
        templateId: templateId,
      );
    }

    await _reminders(userDocId)
        .doc(templateId)
        .set(template, SetOptions(merge: true));

    final now = DateTime.now();

    final minYear = planChanged ? now.year : (now.year - _yearsBack);

    final instanceIds = await syncInstancesFromTemplate(
      userDocId: userDocId,
      templateId: templateId,
      templateData: template,
      minInstanceYear: minYear,
    );

    await _purgeTemplateFromCalendar(
      userDocId: userDocId,
      templateId: templateId,
    );

    await _dedupeYearlySeriesAfterSync(
      userDocId: userDocId,
      templateId: templateId,
      expectedInstanceIds: instanceIds,
      anchorMonth: month,
      anchorDay: day,
    );

    await _purgeForeignYearlyOnSameAnchor(
      userDocId: userDocId,
      keepTemplateId: templateId,
      keepTitle: title,
      anchorMonth: month,
      anchorDay: day,
    );

    await _notifySeriesResynced(
      userDocId: userDocId,
      templateId: templateId,
      templateBefore: templateBefore,
      templateAfter: template,
      anchorCalendarDay: anchorCalendarDay,
      startHHmm: startHHmm,
      instanceIds: instanceIds,
    );
  }

  /// Remove só a ocorrência do ano (mantém os demais anos da série).

  static Future<void> deleteYearlyInstanceOnly({
    required String userDocId,
    required String instanceReminderDocId,
    Map<String, dynamic>? instanceData,
  }) async {
    if (userDocId.isEmpty || instanceReminderDocId.isEmpty) return;

    Map<String, dynamic>? data = instanceData;

    if (data == null) {
      try {
        data = (await _reminders(userDocId).doc(instanceReminderDocId).get())
            .data();
      } catch (_) {}
    }

    final templateId = data != null
        ? templateIdFromReminderData(data, instanceReminderDocId)
        : null;

    final year = data != null
        ? instanceYearFromData(data, docId: instanceReminderDocId)
        : null;

    // Série por dia da semana (id …_yAAAAmMMdDD): exclui só AQUELA data.
    // Antes excluía o ano inteiro e a próxima sincronização apagava todas as
    // ocorrências do ano.
    final dayMatch = _instanceDayIdRe.firstMatch(instanceReminderDocId);
    DateTime? instanceDay;
    if (dayMatch != null) {
      instanceDay = DateTime(
        int.parse(dayMatch.group(1)!),
        int.parse(dayMatch.group(2)!),
        int.parse(dayMatch.group(3)!),
      );
    } else if (data != null && weekdaysFromData(data).isNotEmpty) {
      final raw = data['date'];
      if (raw is Timestamp) {
        final d = raw.toDate();
        instanceDay = DateTime(d.year, d.month, d.day);
      }
    }

    if (templateId != null && instanceDay != null) {
      try {
        await _reminders(userDocId).doc(templateId).set({
          'yearlyRepeatExcludedDates':
              FieldValue.arrayUnion([excludedDateKey(instanceDay)]),
          'updatedAt': FieldValue.serverTimestamp(),
        }, SetOptions(merge: true));
      } catch (_) {}
    } else if (templateId != null && year != null) {
      try {
        await _reminders(userDocId).doc(templateId).set({
          'yearlyRepeatExcludedYears': FieldValue.arrayUnion([year]),
          'updatedAt': FieldValue.serverTimestamp(),
        }, SetOptions(merge: true));
      } catch (_) {}
    }

    await ExpressCompromissoAgendaSync.deleteLinkedFromScaleDoc(
      userDocId: userDocId,
      scaleDocId:
          ExpressCompromissoAgendaSync.scaleDocId(instanceReminderDocId),
    );

    unawaited(AgendaNotificationRescheduleHelper.afterItemChanged(
      userDocId: userDocId,
      queueRebuild: true,
    ));
  }

  /// Resolve o ID do modelo a partir de um lembrete (modelo ou ocorrência).

  static String? templateIdFromReminderData(
      Map<String, dynamic> data, String docId) {
    if (data['isYearlyRepeatTemplate'] == true) return docId;

    final tid = (data['yearlyRepeatTemplateId'] ?? '').toString().trim();

    return tid.isEmpty ? null : tid;
  }

  /// Remove todas as ocorrências da série do calendário (antes de recriar com nova data).

  static Future<void> _clearAllInstancesFromCalendar({
    required String userDocId,
    required String templateId,
  }) async {
    try {
      final snap = await _reminders(userDocId)
          .where('yearlyRepeatTemplateId', isEqualTo: templateId)
          .get();

      for (final doc in snap.docs) {
        await ExpressCompromissoAgendaSync.deleteLinkedFromScaleDoc(
          userDocId: userDocId,
          scaleDocId: ExpressCompromissoAgendaSync.scaleDocId(doc.id),
        );
      }
    } catch (_) {}

    final now = DateTime.now();

    for (var y = now.year - _yearsBack - 3;
        y <= now.year + _yearsForward + 3;
        y++) {
      await ExpressCompromissoAgendaSync.deleteLinkedFromScaleDoc(
        userDocId: userDocId,
        scaleDocId: ExpressCompromissoAgendaSync.scaleDocId(
          instanceDocId(templateId, y),
        ),
      );
    }
  }

  static Future<void> _notifySeriesResynced({
    required String userDocId,
    required String templateId,
    required Map<String, dynamic>? templateBefore,
    required Map<String, dynamic> templateAfter,
    required DateTime anchorCalendarDay,
    required String startHHmm,
    required Set<String> instanceIds,
  }) async {
    await AgendaNotificationRescheduleHelper.afterReminderSave(
      userDocId: userDocId,
      reminderRef: _reminders(userDocId).doc(templateId),
      beforeData: templateBefore,
      newDate: anchorCalendarDay,
      newTimeHHmm: startHHmm,
      afterPlanSnapshot: templateAfter,
    );

    final now = DateTime.now();

    for (final id in instanceIds) {
      final y = instanceYearFromData(const {}, docId: id);

      if (y != null && y >= now.year) {
        try {
          await _reminders(userDocId).doc(id).set({
            'agendaNotifResyncAt': FieldValue.serverTimestamp(),
          }, SetOptions(merge: true));
        } catch (_) {}
      }
    }

    unawaited(AgendaNotificationsRefresher.refresh(uid: userDocId));
  }

  /// Sincroniza ocorrências ano a ano (modelo não aparece no calendário).

  static Future<Set<String>> syncInstancesFromTemplate({
    required String userDocId,
    required String templateId,
    required Map<String, dynamic> templateData,
    int? minInstanceYear,
  }) async {
    if (userDocId.isEmpty || templateId.isEmpty) return {};

    await _reminders(userDocId).doc(templateId).set({
      'isYearlyRepeatTemplate': true,
      'repeatYearly': true,
      'updatedAt': FieldValue.serverTimestamp(),
    }, SetOptions(merge: true));

    final month = (templateData['yearlyRepeatMonth'] as num?)?.toInt() ??
        (templateData['date'] as Timestamp?)?.toDate().month ??
        1;

    final day = (templateData['yearlyRepeatDay'] as num?)?.toInt() ??
        (templateData['date'] as Timestamp?)?.toDate().day ??
        1;

    final title = (templateData['title'] ?? 'Compromisso').toString();

    final notes = mergeUserNotesWithYearlyLine(
      userNotes: (templateData['notes'] ?? '').toString(),
      month: month,
      day: day,
    );

    final startHHmm = (templateData['time'] ?? '09:00').toString();

    final endHHmm = (templateData['endTime'] ?? '10:00').toString();

    final colorHex =
        (templateData['colorHex'] ?? kAgendaCompromissoDefaultColor).toString();

    final weekdays = weekdaysFromData(templateData);

    final excluded = excludedYearsFromData(templateData);

    final excludedDates = excludedDatesFromData(templateData);

    final now = DateTime.now();

    final y0 = minInstanceYear ?? (now.year - _yearsBack);

    final y1 = now.year + _yearsForward;

    final expectedIds = <String>{};

    for (var y = y0; y <= y1; y++) {
      if (excluded.contains(y)) continue;

      final dates = _datesForYear(
        year: y,
        anchorMonth: month,
        anchorDay: day,
        weekdays: weekdays,
      );

      for (final date in dates) {
        if (excludedDates.contains(excludedDateKey(date))) continue;

        final instId = instanceDocId(
          templateId,
          y,
          month: weekdays.isNotEmpty ? date.month : null,
          day: weekdays.isNotEmpty ? date.day : null,
        );

        expectedIds.add(instId);

        await _upsertInstance(
          userDocId: userDocId,
          templateId: templateId,
          instId: instId,
          templateData: templateData,
          title: title,
          notes: notes,
          startHHmm: startHHmm,
          endHHmm: endHHmm,
          colorHex: colorHex,
          month: month,
          day: day,
          instanceYear: y,
          date: date,
        );
      }
    }

    await _pruneOrphanInstances(
      userDocId: userDocId,
      templateId: templateId,
      keepIds: expectedIds,
      excludedYears: excluded,
    );

    await _dedupeYearlySeriesAfterSync(
      userDocId: userDocId,
      templateId: templateId,
      expectedInstanceIds: expectedIds,
      anchorMonth: month,
      anchorDay: day,
    );

    await _purgeForeignYearlyOnSameAnchor(
      userDocId: userDocId,
      keepTemplateId: templateId,
      keepTitle: title,
      anchorMonth: month,
      anchorDay: day,
    );

    return expectedIds;
  }

  static List<DateTime> _datesForYear({
    required int year,
    required int anchorMonth,
    required int anchorDay,
    required List<int> weekdays,
  }) {
    if (weekdays.isEmpty) {
      return [anchorDate(year, anchorMonth, anchorDay)];
    }

    final out = <DateTime>[];

    for (var m = 1; m <= 12; m++) {
      final last = DateTime(year, m + 1, 0).day;

      for (var d = 1; d <= last; d++) {
        final dt = DateTime(year, m, d);

        if (weekdays.contains(dt.weekday)) {
          out.add(dt);
        }
      }
    }

    return out;
  }

  static Future<void> _upsertInstance({
    required String userDocId,
    required String templateId,
    required String instId,
    required Map<String, dynamic> templateData,
    required String title,
    required String notes,
    required String startHHmm,
    required String endHHmm,
    required String colorHex,
    required int month,
    required int day,
    required int instanceYear,
    required DateTime date,
  }) async {
    final instRef = _reminders(userDocId).doc(instId);

    Map<String, dynamic>? instBefore;

    try {
      instBefore = (await instRef.get()).data();
    } catch (_) {}

    final payload = _basePayload(
      title: title,
      notes: notes,
      startHHmm: startHHmm,
      endHHmm: endHHmm,
      colorHex: colorHex,
      month: month,
      day: day,
      isTemplate: false,
      templateId: templateId,
      instanceYear: instanceYear,
      date: date,
      yearlyRepeatWeekdays: weekdaysFromData(templateData),
    );
    payload['reminderLeads'] = FieldValue.delete();
    payload['notificationSoundId'] = FieldValue.delete();
    payload['notificationDeliveryMode'] = FieldValue.delete();
    // «Despertar» da série vale para cada ocorrência.
    final despertarSerie = DespertarItem.fromData(templateData);
    if (despertarSerie != null) {
      payload[DespertarItem.campo] = despertarSerie.toMap();
    }
    // Emoji/ícone da série (FieldValue no modelo = removido → remove aqui).
    final simboloSerie = templateData[kCommitmentSymbolField];
    final simbolo = simboloSerie is String ? simboloSerie.trim() : '';
    payload[kCommitmentSymbolField] =
        simbolo.isEmpty ? FieldValue.delete() : simbolo;

    final instAfterPlan = instBefore != null
        ? (Map<String, dynamic>.from(instBefore)..addAll(payload))
        : null;

    final needsDeliveryReset = instBefore == null ||
        AgendaDeliveryReset.reminderScheduleChanged(
          instBefore,
          date,
          startHHmm,
        ) ||
        (instAfterPlan != null &&
            AgendaDeliveryReset.reminderNotifyPlanChanged(
              instBefore,
              instAfterPlan,
            ));

    if (needsDeliveryReset) {
      payload.addAll(AgendaDeliveryReset.clearDeliveryFields());
    }

    payload['agendaLoginDaySyncAt'] = FieldValue.serverTimestamp();

    await instRef.set(payload, SetOptions(merge: true));

    await AgendaScaleMirrorService.upsert(
      userDocId: userDocId,
      agendaId: instId,
      type: AgendaMirrorType.compromisso,
      label: title,
      date: date,
      startHHmm: startHHmm,
      endHHmm: endHHmm,
      colorHex: colorHex,
      notes: notes,
      createdByLancamentoExpresso:
          (templateData['source'] ?? '').toString() == 'lancamento_expresso',
      commitmentSymbol: simbolo,
    );
  }

  static Future<void> _pruneOrphanInstances({
    required String userDocId,
    required String templateId,
    required Set<String> keepIds,
    required Set<int> excludedYears,
  }) async {
    try {
      final snap = await _reminders(userDocId)
          .where('yearlyRepeatTemplateId', isEqualTo: templateId)
          .get();

      for (final doc in snap.docs) {
        final y = instanceYearFromData(doc.data(), docId: doc.id);

        if ((y != null && excludedYears.contains(y)) ||
            !keepIds.contains(doc.id)) {
          if (doc.id != templateId) {
            await _deleteYearlyOccurrenceAndMirror(
              userDocId: userDocId,
              reminderId: doc.id,
            );
          }
        }
      }
    } catch (_) {}
  }

  /// Remove linhas «mestre» antigas que duplicavam a mesma data no 1.º ano.

  static Future<void> _removeLegacyDuplicateMasters({
    required String userDocId,
    required String templateId,
    required int anchorMonth,
    required int anchorDay,
  }) async {
    try {
      final snap = await _reminders(userDocId)
          .where('repeatYearly', isEqualTo: true)
          .get();

      for (final doc in snap.docs) {
        if (doc.id == templateId) continue;

        if (isYearlyInstanceDocId(doc.id)) continue;

        final data = doc.data();

        if (data['isYearlyRepeatTemplate'] == true) continue;

        final tid = (data['yearlyRepeatTemplateId'] ?? '').toString().trim();

        // Só a PRÓPRIA série (vínculo explícito). Legado sem vínculo é tratado em
        // [_purgeForeignYearlyOnSameAnchor] e exige título exatamente igual — antes
        // `tid.isEmpty && mesma data` apagava outra série anual do mesmo dia.
        final isGhostMaster = tid == templateId;

        if (!isGhostMaster) continue;

        if (isYearlyInstanceDocId(doc.id)) continue;

        await _deleteYearlyOccurrenceAndMirror(
          userDocId: userDocId,
          reminderId: doc.id,
        );
      }
    } catch (_) {}
  }

  /// Remove série completa (modelo + ocorrências + espelhos).

  static Future<void> deleteYearlySeries({
    required String userDocId,
    required String templateId,
  }) async {
    if (userDocId.isEmpty || templateId.isEmpty) return;

    try {
      final snap = await _reminders(userDocId)
          .where('yearlyRepeatTemplateId', isEqualTo: templateId)
          .get();

      for (final doc in snap.docs) {
        await ExpressCompromissoAgendaSync.deleteLinkedFromScaleDoc(
          userDocId: userDocId,
          scaleDocId: ExpressCompromissoAgendaSync.scaleDocId(doc.id),
        );
      }
    } catch (_) {}

    final now = DateTime.now();

    for (var y = now.year - _yearsBack - 2;
        y <= now.year + _yearsForward + 2;
        y++) {
      final instId = instanceDocId(templateId, y);

      await ExpressCompromissoAgendaSync.deleteLinkedFromScaleDoc(
        userDocId: userDocId,
        scaleDocId: ExpressCompromissoAgendaSync.scaleDocId(instId),
      );
    }

    try {
      await _reminders(userDocId).doc(templateId).delete();
    } catch (_) {}

    unawaited(AgendaNotificationRescheduleHelper.afterItemChanged(
      userDocId: userDocId,
      queueRebuild: true,
    ));
  }

  static Map<String, dynamic> _basePayload({
    required String title,
    required String notes,
    required String startHHmm,
    required String endHHmm,
    required String colorHex,
    List<int>? reminderLeads,
    String? notificationSoundId,
    String? notificationDeliveryMode,
    required int month,
    required int day,
    required bool isTemplate,
    required String templateId,
    int? instanceYear,
    DateTime? date,
    List<int>? yearlyRepeatWeekdays,
    Set<int>? excludedYears,
    Set<String>? excludedDates,
  }) {
    final d = date ?? anchorDate(DateTime.now().year, month, day);

    final payload = <String, dynamic>{
      'type': 'compromisso',
      'title': title.trim().isEmpty ? 'Compromisso' : title.trim(),
      'notes': notes,
      'date': Timestamp.fromDate(DateTime(d.year, d.month, d.day)),
      'time': startHHmm,
      'endTime': endHHmm,
      'colorHex': colorHex,
      'status': 'EM_ABERTO',
      'done': false,
      'repeatYearly': true,
      'yearlyRepeatMonth': month,
      'yearlyRepeatDay': day,
      'yearlyRepeatTemplateId': isTemplate ? null : templateId,
      'isYearlyRepeatTemplate': isTemplate,
      'updatedAt': FieldValue.serverTimestamp(),
    };

    if (instanceYear != null) {
      payload['yearlyRepeatInstanceYear'] = instanceYear;
    }

    if (yearlyRepeatWeekdays != null && yearlyRepeatWeekdays.isNotEmpty) {
      payload['yearlyRepeatWeekdays'] = yearlyRepeatWeekdays;
    }
    // Campo vazio: omitir no create (set sem merge). Remoção via merge em [updateYearlySeries].

    if (isTemplate && excludedYears != null && excludedYears.isNotEmpty) {
      payload['yearlyRepeatExcludedYears'] = excludedYears.toList()..sort();
    }

    if (isTemplate && excludedDates != null && excludedDates.isNotEmpty) {
      payload['yearlyRepeatExcludedDates'] = excludedDates.toList()..sort();
    }

    if (isTemplate) {
      payload['createdAt'] = FieldValue.serverTimestamp();

      payload['source'] = 'yearly_repeat_template';
    } else {
      payload['source'] = 'yearly_repeat_instance';

      payload['lancamentoOrigem'] = 'yearly_repeat';
    }

    return payload;
  }
}
