/// Dicas diárias de economia, investimentos e poupança.
/// Rotacionadas pelo dia do ano para mostrar uma por dia (quando o usuário ativar).
const List<String> kFinanceTips = [
  'Reserve pelo menos 10% da renda para poupança antes de gastar.',
  'Pague suas contas em dia para evitar juros e multas.',
  'Anote todos os gastos: quem controla, economiza.',
  'Compare preços e use listas antes de ir ao supermercado.',
  'Crie uma reserva de emergência de 3 a 6 meses de despesas.',
  'Evite parcelar no cartão quando puder pagar à vista.',
  'Invista o que sobrar após a reserva de emergência.',
  'Reduza assinaturas que você pouco usa (streaming, apps).',
  'Poupança rende pouco: considere Tesouro Direto para prazos maiores.',
  'Separe um valor fixo por mês para lazer, sem culpa.',
  'Negocie dívidas: muitas vezes é possível reduzir juros.',
  'Use a regra 50/30/20: 50% necessidades, 30% desejos, 20% poupança.',
  'Evite compras por impulso: espere 24h antes de comprar.',
  'Planeje as refeições da semana para reduzir desperdício e delivery.',
  'Revise contratos (celular, internet, plano de saúde) uma vez por ano.',
  'Invista em educação financeira: livros e cursos pagam-se no longo prazo.',
  'Tenha apenas um cartão de crédito se tende a gastar demais.',
  'Automátize a poupança: transferência no dia do salário.',
  'Guarde trocados e notas em um cofrinho e deposite todo mês.',
  'Defina metas de curto, médio e longo prazo para manter o foco.',
  'Para comprar um carro: pesquise à vista e usado; evite financiamento longo.',
  'Pague primeiro as dívidas com maior juro (cartão, cheque especial).',
  'Celebre pequenas vitórias: cada meta batida motiva a próxima.',
  'Use o 13º e férias para abater dívidas ou reforçar a reserva.',
  'Antes de assinar um financiamento, simule o total que vai pagar.',
  'Um café por dia = R\$ 150/mês. Pequenos gastos somam muito.',
  'Mantenha uma planilha ou app: quem anota gasta até 20% menos.',
  'Combine com a família um teto de gastos no mês e revejam juntos.',
  'Invista em CDB ou Tesouro Selic para reserva com liquidez.',
  'Se receber aumento, destine metade à poupança antes de acostumar.',
  'Para viagem: abra uma meta e deposite todo mês até a data.',
  'Evite empréstimo consignado para quitar cartão: renegocie a dívida.',
  'Faça uma “detox” de um mês: só gastos essenciais e veja o que sobra.',
  'Compre à vista quando houver desconto; senão, parcele sem juros.',
  'Reserva de emergência primeiro; depois pense em investir em risco.',
  'Revise assinaturas: cancele o que não usa há mais de 3 meses.',
  'Para reforma: estipule o valor total e guarde por etapa.',
  'Ensine as crianças a poupar: mesada com cofrinho para um sonho.',
];
